server:
  port: 8070

jwt:
  secret: ${KEYSECRET_SECURITY:eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.nZU_gPcMXkWpkCUpJceSxS7lSickF0tTImHhAR949Z-Nt69LgW8G6lid-mqd9B579tYM8C4FN2jdhR2VRMsjtA}
  expiration: ${EXPIRE_DAYS_SECURITY:3600000}

spring:
  data:
    mongodb:
      uri: mongodb+srv://lilianagallegom:1dAPD680s34zIcte@cluster0.4idvqkx.mongodb.net/?retryWrites=true&w=majority

      database: Traceability

management:
  endpoints:
    web:
      exposure:
        include: "*"

my:
  variables: